### PR TITLE
Use currentlyFocusInput instead of currentlyFocusedField

### PR DESCRIPTION
**Pull request by xapai**
- Change soon-to-be deprecated currentlyFocusedField method to newly currentlyFocusedInput

### CODE REVIEW

**Comment by octopitus** [comment]
Thanks @xapai. But i'm suggesting we should fallback to `currentlyFocusedField` if it exists, in case people use the latest version of the library with an old RN version, as `currentlyFocusedInput` is only available in 0.63.

```js
const node = TextInput.State.currentlyFocusedField 
  ? TextInput.State.currentlyFocusedField()
  : findNodeHandler(TextInput.State.currentlyFocusedInput());
```

**Comment by xapai** [comment]
> Thanks @xapai. But i'm suggesting we should fallback to `currentlyFocusedField` if it exists, in case people use the latest version of the library with an old RN version, as `currentlyFocusedInput` is only available in 0.63.

Yeah, sure. You are right. Will fix that.

**Comment by burgioandrea** [comment]
Hello,
any updates on this?

**Comment by MathisGuilhin** [comment]
Any updates on this PR?

**Comment by keeprock** [comment]
Guys, I forgot about this PR. Good that **octopitus** taken over and finished it. Thanks!

**Pull request merged**
