### PR TITLE
add onClose prop for callback when the panel is closed

### PR DESCRIPTION
**Pull request by DaniAkash**
Will add an onClose prop which will be called every time the panel is closed.

### CODE REVIEW

**Comment by octopitus** [comment]
The word `close` may not the right term if the draggableRange has bottom value higher 0. `close` is when something is going to be dismissed or gone (E.g Close modal, close drawer, close database connection...).

If you want is to be notified when the panel reaches the bottom, you can use `onMomentumDragEnd` or [InteractionManager](https://facebook.github.io/react-native/docs/interactionmanager#docsNav):

```js
_handleOnMomentumEnd(value) {
  // Compare the value with the bottom of draggableRange
  if (value === 0) {
  
  }
}

// This method is called when you click a button to hide the panel
_showPanel() {
  this._panel.hide()

  InteractionManager.runAfterInteractions(() => {
    // ...long-running synchronous task...
  });
}


<Panel
  ref={c => this._panel = c}
  onMomentumDragEnd={this._handleOnMomentumDragEnd}
/>
```

**Comment by DaniAkash** [comment]
Still i'd like to have a single handler to handle this. Will `onHide` be the right term?

**Comment by DaniAkash** [comment]
Sure it will work. I'll update my PR

**Comment by rgoldiez** [comment]
> Sure it will work. I'll update my PR

Any plans to update this PR?

**Comment by DaniAkash** [comment]
@rgoldiez sorry I was on a trip. Will update tomorrow

**Comment by daviswhitehead** [comment]
Any chance we can get this PR merged? I'd love to use the onClose functionality!

**Comment by jaredegan** [comment]
This PR seems like exactly what I need, but I see two issues with it:

- Conflict in `README.md`
- The types (defined in `index.d.ts`) have not been updated to include the new prop.

**Comment by DaniAkash** [comment]
@jaredegan i'll update the PR. Its been a long time

**Comment by jaredegan** [comment]
Thanks, Dani! I know how these things go, hopefully we can get it merged in.

**Comment by DaniAkash** [comment]
@jaredegan I have updated the PR

**Comment by octopitus** [comment]
Published in v2.4.0

**Comment by jaredegan** [comment]
Excellent! 🤘

**Comment by jaredegan** [comment]
@octopitus looks like 2.4.0 was not successfully published: https://www.npmjs.com/package/rn-sliding-up-panel

**Comment by octopitus** [comment]
@jaredegan Opps I published using wrong registry config 🤦‍♂ .

**Pull request merged**
